# Understanding Pandas Series and DataFrames - Lab

## Introduction

In this lab, let's get some hands on practice working with data cleanup using Pandas.

## Objectives
You will be able to:

* Manipulate columns in DataFrames (df.rename, df.drop)
* Manipulate the index in DataFrames (df.reindex, df.drop, df.rename)
* Manipulate column datatypes

## Let's get started!

In [133]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
df = pd.read_csv('turnstile_180901.txt')
print(len(df))
df.head()

## Rename all the columns to lower case

In [ ]:
df.columns = [i.lower() for i in df.columns]#Your code here
df

# df.columns = df.columns.str.lower()#Your code here

## Change the Index to be the Line Names

In [86]:
df = df.set_index('linename')#Your code here

# Change the index back

In [87]:
df = df.reset_index()# Your code here

## Create another column 'Num_Lines' that is a count of how many lines pass through a station. Then sort your dataframe by this column in descending order

In [89]:
df.insert(1,'Num_Lines',0) # Your code here
df.sort_values(by='Num_Lines', ascending=False)

,linename,Num_Lines,c/a,unit,scp,station,division,date,time,desc,entries,exits
0,NQR456W,0,A002,R051,02-00-00,59 ST,BMT,08/25/2018,00:00:00,REGULAR,6736067,2283184
131814,1237ACENQRS,0,R147,R033,04-00-06,TIMES SQ-42 ST,IRT,08/27/2018,04:00:00,REGULAR,13412952,3081720
131744,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/29/2018,08:00:00,REGULAR,15678421,7412830
131745,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/29/2018,12:00:00,REGULAR,15678935,7413149
131746,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/29/2018,16:00:00,REGULAR,15679412,7413261
131747,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/29/2018,20:00:00,REGULAR,15680415,7413502
131748,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/30/2018,00:00:00,REGULAR,15681074,7413632
131749,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/30/2018,04:00:00,REGULAR,15681198,7413672
131750,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/30/2018,08:00:00,REGULAR,15681342,7413788
131751,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/30/2018,12:00:00,REGULAR,15681869,7414253
131752,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/30/2018,16:00:00,REGULAR,15682414,7414593
131753,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/30/2018,20:00:00,REGULAR,15683445,7414922
131754,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/31/2018,00:00:00,REGULAR,15684222,7415091
131755,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/31/2018,04:00:00,REGULAR,15684367,7415143
131756,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/31/2018,08:00:00,REGULAR,15684477,7415283
131757,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/31/2018,12:00:00,REGULAR,15684891,7415702
131758,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/31/2018,16:00:00,REGULAR,15685553,7416088
131759,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/31/2018,20:00:00,REGULAR,15686330,7416463
131760,1237ACENQRS,0,R147,R033,04-00-05,TIMES SQ-42 ST,IRT,08/25/2018,00:00:00,REGULAR,12980176,4715354
131761,1237ACENQRS,0,R147,R033,04-00-05,TIMES SQ-42 ST,IRT,08/25/2018,04:00:00,REGULAR,12980386,4715390
131762,1237ACENQRS,0,R147,R033,04-00-05,TIMES SQ-42 ST,IRT,08/25/2018,08:00:00,REGULAR,12980434,4715420
131763,1237ACENQRS,0,R147,R033,04-00-05,TIMES SQ-42 ST,IRT,08/25/2018,12:00:00,REGULAR,12980685,4715610
131764,1237ACENQRS,0,R147,R033,04-00-05,TIMES SQ-42 ST,IRT,08/25/2018,16:00:00,REGULAR,12981106,4715939
131743,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/29/2018,04:00:00,REGULAR,15678294,7412737
131742,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/29/2018,00:00:00,REGULAR,15678156,7412701
131741,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/28/2018,20:00:00,REGULAR,15677425,7412581
131729,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/26/2018,16:00:00,REGULAR,15671394,7409817
131720,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/25/2018,04:00:00,REGULAR,15667889,7407783
131721,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/25/2018,08:00:00,REGULAR,15667955,7407860
131722,1237ACENQRS,0,R147,R033,04-00-04,TIMES SQ-42 ST,IRT,08/25/2018,12:00:00,REGULAR,15668274,7408097
...,...,...,...,...,...,...,...,...,...,...,...,...
65901,A,0,N138,R355,01-06-00,111 ST,IND,08/30/2018,05:00:00,REGULAR,2533571,803084
65902,A,0,N138,R355,01-06-00,111 ST,IND,08/30/2018,09:00:00,REGULAR,2533902,803088
65903,A,0,N138,R355,01-06-00,111 ST,IND,08/30/2018,13:00:00,REGULAR,2533991,803094
65904,A,0,N138,R355,01-06-00,111 ST,IND,08/30/2018,17:00:00,REGULAR,2534049,803123
65905,A,0,N138,R355,01-06-00,111 ST,IND,08/30/2018,21:00:00,REGULAR,2534073,803207
65885,A,0,N138,R355,01-06-00,111 ST,IND,08/27/2018,13:00:00,REGULAR,2532428,802706
65883,A,0,N138,R355,01-06-00,111 ST,IND,08/27/2018,05:00:00,REGULAR,2532047,802687
65861,A,0,N138,R355,01-04-01,111 ST,IND,08/30/2018,13:00:00,REGULAR,0,350
65871,A,0,N138,R355,01-06-00,111 ST,IND,08/25/2018,05:00:00,REGULAR,2531681,802596
65862,A,0,N138,R355,01-04-01,111 ST,IND,08/30/2018,17:00:00,REGULAR,0,350
65863,A,0,N138,R355,01-04-01,111 ST,IND,08/30/2018,21:00:00,REGULAR,0,350
65864,A,0,N138,R355,01-04-01,111 ST,IND,08/31/2018,01:00:00,REGULAR,0,350
65865,A,0,N138,R355,01-04-01,111 ST,IND,08/31/2018,05:00:00,REGULAR,0,350
65866,A,0,N138,R355,01-04-01,111 ST,IND,08/31/2018,09:00:00,REGULAR,0,350
65867,A,0,N138,R355,01-04-01,111 ST,IND,08/31/2018,13:00:00,REGULAR,0,350
65868,A,0,N138,R355,01-04-01,111 ST,IND,08/31/2018,17:00:00,REGULAR,0,350
65869,A,0,N138,R355,01-04-01,111 ST,IND,08/31/2018,21:00:00,REGULAR,0,350
65870,A,0,N138,R355,01-06-00,111 ST,IND,08/25/2018,01:00:00,REGULAR,2531676,802593
65872,A,0,N138,R355,01-06-00,111 ST,IND,08/25/2018,09:00:00,REGULAR,2531757,802597
65882,A,0,N138,R355,01-06-00,111 ST,IND,08/27/2018,01:00:00,REGULAR,2532031,802685
65873,A,0,N138,R355,01-06-00,111 ST,IND,08/25/2018,13:00:00,REGULAR,2531799,802601
65874,A,0,N138,R355,01-06-00,111 ST,IND,08/25/2018,17:00:00,REGULAR,2531831,802605
65875,A,0,N138,R355,01-06-00,111 ST,IND,08/25/2018,21:00:00,REGULAR,2531855,802639
65876,A,0,N138,R355,01-06-00,111 ST,IND,08/26/2018,01:00:00,REGULAR,2531865,802646
65877,A,0,N138,R355,01-06-00,111 ST,IND,08/26/2018,05:00:00,REGULAR,2531869,802650
65878,A,0,N138,R355,01-06-00,111 ST,IND,08/26/2018,09:00:00,REGULAR,2531917,802653
65879,A,0,N138,R355,01-06-00,111 ST,IND,08/26/2018,13:00:00,REGULAR,2531964,802657
65880,A,0,N138,R355,01-06-00,111 ST,IND,08/26/2018,17:00:00,REGULAR,2531995,802664
65881,A,0,N138,R355,01-06-00,111 ST,IND,08/26/2018,21:00:00,REGULAR,2532019,802676
197624,R,0,TRAM2,R469,00-05-01,RIT-ROOSEVELT,RIT,08/31/2018,21:00:00,REGULAR,5554,348

## Write a function to clean a column name

In [121]:
def clean(col_name):
    cleaned = col_name.lower()#Your code here; whatever you want to do to col_name. Hint: think back to str methods.
    return cleaned
      
    
#  cleaned = [col_name.lower() for col_name in df.columns]
#     return cleaned





clean('Howard')

'howard'

In [122]:
#This is a list comprehension. It applies your clean function to every item in the list.
#We then reassign that to df.columns
#You shouldn't have to change anything here.
#Your function above should work appropriately here.
df.columns = [clean(col) for col in df.columns]

In [123]:
#Checking the output, we can see the results.
df.columns

Index(['linename', 'num_lines', 'c/a', 'unit', 'scp', 'station', 'division',
       'date', 'time', 'desc', 'entries',
       'exits                                                               '],
      dtype='object')

## Group the Data by Day of Week and Plot the Sum of The Numeric Columns

In [132]:
pd.to_datetime(df.date).head()
# df = df.date.dt.day_name().head()#Your code here

AttributeError: 'Series' object has no attribute 'date'

## Group the Data by Weekend/Weekday and Plot the Sum of the Numeric Columns

In [ ]:
#Your code here

## Analysis Question: 

What is misleading about the day of week and weekend/weekday charts you just plotted?

In [ ]:
# Your answer here

## Drop a couple of columns

In [ ]:
# Your code here

## Summary

Great! You practiced your data cleanup-skills using Pandas.